### ISSUE TITLE
Google Sign-In not sending name

### ISSUE THREAD

**Issue by ideen1** [Code-the-Change-YYC/hackathon-management-tool#42]
As well as not creating Dynamo DB record correctly

**Comment by justin-phxm** [comment]
This blog might help

https://docs.amplify.aws/javascript/build-a-backend/auth/concepts/external-identity-providers/#attribute-mapping

**Comment by justin-phxm** [comment]
I get this error after trying to sign up w/ google on localhost:3000

@ideen1 Perhaps I am missing some secrets

![image](https://github.com/user-attachments/assets/ec0b5fe1-88ff-4df8-a52b-774580dd31a0)

**Comment by ideen1** [comment]
Yes you are missing secrets

**Comment by ideen1** [comment]
Thanks for the guides you found! I believe we actually used those to fix this problem. We can close this. Confirming that Google Sign in works.
