### ISSUE TITLE
Can't properly log back in after resetting password

### ISSUE THREAD

**Issue by AnaCoda** [Code-the-Change-YYC/hackathon-management-tool#49]
After resetting my password using "Forgot Password", I tried to log back in and got an error that it couldn't get the user session.
A few minutes later I was somehow able to log in but I had to re-enter my information, and after I did that it said it was updating "undefined" and I couldn't really do anything.

**Comment by ideen1** [comment]
Closing this as the reset password doesn't seem to be affected but rather the personal info collections, which will be fixed by #53 . Please reopen if that doesn't fix the issue
