### ISSUE TITLE
Cannot select yes or not to food option

### ISSUE THREAD

**Issue by AllanKoder** [Code-the-Change-YYC/hackathon-management-tool#50]
I am unable to select yes or not for "Do you want provided food at the hackathon?" during user sign up

![image](https://github.com/Code-the-Change-YYC/hackathon-management-tool/assets/74692833/1026c3c6-889f-44ea-abcc-30642cc950b6)

**Comment by burtonjong** [comment]
![image](https://github.com/user-attachments/assets/f658cac8-a2d8-48d5-a347-37862c002dee)


the select was just named meals instead of willEatMeals.
