### ISSUE TITLE
Profile header does not display full name

### ISSUE THREAD

**Issue by burtonjong** [Code-the-Change-YYC/hackathon-management-tool#61]
Issue that can be addressed pretty easily but its low priority for now:

- instead of getting the first/last name from the useUser() function from UserContext, instead just get the useUser().currentUser.username and use that + a tanstack query to fetch the first and last name (similar to UserForm.tsx)

**Comment by burtonjong** [comment]
Not only this but the other header (the one that contains the logo) also doesnt update and doesnt change to accomodate for the users role

**Comment by ideen1** [comment]
I think this is fixed now right?

> Issue that can be addressed pretty easily but its low priority for now:
> 
> * instead of getting the first/last name from the useUser() function from UserContext, instead just get the useUser().currentUser.username and use that + a tanstack query to fetch the first and last name (similar to UserForm.tsx)

This is not ideal as we would be sending a query for something that is already in the Context. I would prefer to fix the context so it actually updates

**Comment by ideen1** [comment]
@justin-phxm  Can you please invalidate the User key in your update form field query and then this will be fixed?

**Comment by justin-phxm** [comment]
http://localhost:3000/participant

Before:
![image](https://github.com/user-attachments/assets/b2368054-23e3-4dfd-97bf-cc819463530d)

After:
![image](https://github.com/user-attachments/assets/58f59a31-edcd-405c-b263-f7c118734e0b)

**Comment by justin-phxm** [comment]
idk this was more of a design choice than an accidental bug but up to you if you wanna merge.
