### ISSUE TITLE
Switching Tabs on Individual Registration Page repeatedly shows Toast Message

### ISSUE THREAD

**Issue by AllanKoder** [Code-the-Change-YYC/hackathon-management-tool#71]
![image](https://github.com/user-attachments/assets/48c7768f-e0b2-4319-acb3-8c8725f884e7)
This pops up everytime I switch tabs

**Comment by ideen1** [comment]
@justin-phxm In PersonalFormFields, queryKey "user" is used to load a preliminary set of user information. Can we use the userContext to get this information?

**Comment by ideen1** [comment]
This will be addressed by #53 as well as the merge I put in last night. Data is now cached on the front end.
